/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

#include "nsISupports.idl"

interface nsIChannel;
interface nsIURI;

/* nsIEnigMimeHeaderSink is an OpenPGP header sink analagous to
 * nsIMsgSMIMEHeaderSink
 */

[scriptable, uuid(847b3a80-7ab1-11d4-8f02-006008948af5)]
interface nsIEnigMimeHeaderSink : nsISupports
{
  void updateSecurityStatus(in AUTF8String uriSpec,
                            in long exitCode,
                            in unsigned long statusFlags,
                            in wstring keyId,
                            in wstring userId,
                            in wstring sigDetails,
                            in wstring errorMsg,
                            in wstring blockSeparation,
                            in nsIURI uri,
                            in wstring encToDetails,
                            in wstring mimePartNumber);

  void modifyMessageHeaders(in nsIURI uri,
                            in wstring headerData,
                            in wstring mimePartNumber);

  void handleSMimeMessage(in nsIURI uri);
};


///////////////////////////////////////////////////////////////////////////////
