/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */


#include "nsISupports.idl"
#include "nsIMsgSMIMECompFields.idl"

/**
 * MsgCompose security info for Enigmail
 */
[scriptable, uuid(847b3a30-7ab1-11d4-8f02-006008948af5)]
interface nsIEnigMsgCompFields : nsIMsgSMIMECompFields
{
  /**
   * See nsIEnigmail.idl for valid uiFlags and sendFlags
   */

  void init(in nsIMsgSMIMECompFields smimeCompFields);

  attribute unsigned long UIFlags;

  attribute unsigned long sendFlags;

  attribute AString senderEmailAddr;

  attribute AString recipients;

  attribute AString bccRecipients;

  attribute AString originalSubject;

  attribute AString originalReferences;
};

%{C++

#define NS_ENIGMSGCOMPFIELDS_CLASSNAME  "Enigmail Msg Compose Fields"
#define NS_ENIGMSGCOMPFIELDS_CONTRACTID "@mozdev.org/enigmail/composefields;1"

#define NS_ENIGMSGCOMPFIELDS_CID                          \
{ /* 847b3a31-7ab1-11d4-8f02-006008948af5 */     \
   0x847b3a31, 0x7ab1, 0x11d4,                   \
{0x8f, 0x02, 0x00, 0x60, 0x08, 0x94, 0x8a, 0xf5} }

%}

//////////////////////////////////////////////////////////////////////////////
