/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */


#include "nsISupports.idl"

interface nsIDOMNode;

/**
 * EnigMime service
 */
[scriptable, uuid(847b3a40-7ab1-11d4-8f02-006008948af5)]
interface nsIEnigMimeService : nsISupports
{

  void init();
  readonly attribute boolean initialized;

  readonly attribute string version;

  AString getPlainText(in nsIDOMNode domNode, in wstring findStr);

  void sleep(in unsigned long miliSeconds);

  /**
   * Returns random number with specified number of digits,
   * in hexadecimal format.
   * CAUTION: This call uses the entropy source, which may cause the
   * calling thread to block until sufficient entropy is collected.
   */
  string getRandomHex(in unsigned long nDigits);

};

%{C++

#define NS_ENIGMIMESERVICE_CONTRACTID "@mozdev.org/enigmail/enigmimeservice;1"

#define NS_ENIGMIMESERVICE_CLASSNAME  "Enigmail Mime Service"

#define APPLICATION_XENIGMAIL_DUMMY "application/x-enigmail-dummy"

#define MULTIPART_ENCRYPTED "multipart/encrypted"

#define APPLICATION_PGP "application/pgp"

#define NS_ENIGDUMMYHANDLER_CONTRACTID "@mozilla.org/mimecth;1?type=" APPLICATION_XENIGMAIL_DUMMY

#define NS_ENIGENCRYPTEDHANDLER_CONTRACTID "@mozilla.org/mimecth;1?type=" MULTIPART_ENCRYPTED

#define NS_ENIGPGPHANDLER_CONTRACTID "@mozilla.org/mimecth;1?type=" APPLICATION_PGP

#define NS_ENIGCONTENTHANDLER_CLASSNAME  "Enigmail Content Handler"


#define NS_ENIGCONTENTHANDLERFACTORY_CONTRACTID "@mozilla.org/enigmail/contenthandler-factory;1"

#define NS_ENIGCONTENTHANDLERFACTORY_CLASSNAME "Enigmail Content Handler Factory"

#define NS_ENIGMIMESERVICE_CID                   \
{ /* 847b3a41-7ab1-11d4-8f02-006008948af5 */     \
   0x847b3a41, 0x7ab1, 0x11d4,                   \
{0x8f, 0x02, 0x00, 0x60, 0x08, 0x94, 0x8a, 0xf5} }

#define NS_ENIGCONTENTHANDLER_CID                \
{ /* 847b3a51-7ab1-11d4-8f02-006008948af5 */     \
   0x847b3a51, 0x7ab1, 0x11d4,                   \
{0x8f, 0x02, 0x00, 0x60, 0x08, 0x94, 0x8a, 0xf5} }

#define NS_ENIGCONTENTHANDLERFACTORY_CID         \
{ /* 847b3a52-7ab1-11d4-8f02-006008948af5 */     \
   0x847b3a52, 0x7ab1, 0x11d4,                   \
{0x8f, 0x02, 0x00, 0x60, 0x08, 0x94, 0x8a, 0xf5} }

%}

//////////////////////////////////////////////////////////////////////////////
