#!/bin/sh

# **** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
#
# The contents of this file are subject to the Mozilla Public
# License Version 1.1 (the "MPL"); you may not use this file
# except in compliance with the MPL. You may obtain a copy of
# the MPL at http://www.mozilla.org/MPL/
#
# Software distributed under the MPL is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the MPL for the specific language governing
# rights and limitations under the MPL.
#
# The Original Code is Enigmail.
#
# The Initial Developer of the Original Code is Patrick Brunschwig.
# Portions created by Patrick Brunschwig <patrick@enigmail.net> are
# Copyright (C) 2004 Patrick Brunschwig. All Rights Reserved.
#
# Contributor(s):
#
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
# ***** END LICENSE BLOCK *****

#
# This script generates the Enigmail XPI
#

echo "genxpi: Generating $1 in $3"

if [ $# -lt 5 ]; then
  echo "Wrong number of parameters"
  exit 1
fi

xpiFile=$1
xpiVersion="$2"
distDir="$3"
srcDir=$4
xpiModule=$5
enableLang=$6

cd ${srcDir}
cwd=`pwd`
cd "$distDir"
targetDir=`pwd`
cd "$cwd"

cp ${srcDir}/package/install.rdf ${targetDir}/install.rdf

# Prepare chrome.manifest
cat  ${srcDir}/package/chrome.manifest \
> ${targetDir}/chrome.manifest

# Prepare languages other than en-US

if [ "$enableLang" = "yes" ]; then
  if [ -s ${srcDir}/lang/current-languages.txt ]; then
    echo '' >> ${targetDir}/chrome.manifest
    echo '# Additional languages' >> ${targetDir}/chrome.manifest

    for lang in `cat ${srcDir}/lang/current-languages.txt`; do
      echo 'locale        enigmail    '$lang'       jar:chrome/enigmail.jar!/locale/'$lang'/' >> ${targetDir}/chrome.manifest
    done
  fi
fi


# cd ${srcDir}/package
cd "$targetDir"


mkdir -p "${targetDir}/wrappers"

cp ${cwd}/util/gpg-agent-wrapper.sh wrappers

echo "Creating ${xpiFile} file"

zip --must-match\
    ../${xpiFile} \
    components/${xpiModule}.xpt \
    components/${xpiModule}.js \
    components/prefs-service.js \
    components/msgCompFields.js \
    components/pgpmimeHandler.js \
    components/mimeEncrypt.js \
    defaults/preferences/enigmail.js \
    modules/app.jsm \
    modules/armor.jsm \
    modules/attachment.jsm \
    modules/card.jsm \
    modules/commandLine.jsm \
    modules/configure.jsm \
    modules/constants.jsm \
    modules/data.jsm \
    modules/decryption.jsm \
    modules/decryptPermanently.jsm \
    modules/dialog.jsm \
    modules/encryption.jsm \
    modules/core.jsm \
    modules/errorHandling.jsm \
    modules/funcs.jsm \
    modules/gpgAgent.jsm \
    modules/protocolHandler.jsm \
    modules/events.jsm \
    modules/execution.jsm \
    modules/files.jsm \
    modules/filters.jsm \
    modules/fixExchangeMsg.jsm \
    modules/glodaMime.jsm \
    modules/glodaUtils.jsm \
    modules/gpg.jsm \
    modules/hash.jsm \
    modules/httpProxy.jsm \
    modules/installGnuPG.jsm \
    modules/key.jsm \
    modules/keyEditor.jsm \
    modules/keyRing.jsm \
    modules/keyserver.jsm \
    modules/lazy.jsm \
    modules/locale.jsm \
    modules/log.jsm \
    modules/mime.jsm \
    modules/mimeDecrypt.jsm \
    modules/mimeVerify.jsm \
    modules/os.jsm \
    modules/passwordCheck.jsm \
    modules/passwords.jsm \
    modules/pipeConsole.jsm \
    modules/prefs.jsm \
    modules/promise.jsm \
    modules/rules.jsm \
    modules/streams.jsm \
    modules/subprocess.jsm \
    modules/subprocess_worker_unix.js \
    modules/subprocess_worker_win.js \
    modules/time.jsm \
    modules/timer.jsm \
    modules/trust.jsm \
    modules/uris.jsm \
    modules/verify.jsm \
    modules/windows.jsm \
    wrappers/gpg-agent-wrapper.sh \
    chrome/${xpiModule}.jar \
    chrome.manifest \
    install.rdf
